insert into opinions (opinion, counter) values ('BART should be free for everyone', 43);
insert into opinions (opinion, counter) values ('Charles is pretty neat', 44);
insert into opinions (opinion, counter) values ('JavaScript Thursdays is amazing', 45);
insert into opinions (opinion, counter) values ('JAVASCRIPT THURSDAYS IS AMAZING', 45);
insert into opinions (opinion, counter) values ('javascript thursdays is amazing', 45);
insert into opinions (opinion, counter) values ('Catch a man a fish, and you can sell it to him. Teach a man to fish, and you ruin a wonderful business opportunity.', 69);
insert into opinions (opinion, counter) values ('Landlords, like all other men, love to reap where they never sowed.', 32);
insert into opinions (opinion, counter) values ('The production of too many useful things results in too many useless people.', 4);
insert into opinions (opinion, counter) values ('Experience praises the most happy the one who made the most people happy.', 1);
insert into opinions (opinion, counter) values ('Necessity is blind until it becomes conscious. Freedom is the consciousness of necessity.', 32);
insert into opinions (opinion, counter) values ('Religion is the sigh of the oppressed creature, the heart of a heartless world, and the soul of soulless conditions. It is the opium of the people.', 100);
insert into opinions (opinion, counter) values ('The human being is in the most literal sense a political animal, not merely a gregarious animal, but an animal which can individuate itself only in the midst of society.', 99);
insert into opinions (opinion, counter) values ('Necessity is blind until it becomes conscious. Freedom is the consciousness of necessity.', 88);
insert into opinions (opinion, counter) values ('We should not say that one man’s hour is worth another man’s hour, but rather that one man during an hour is worth just as much as another man during an hour. Time is everything, man is nothing: he is at the most time’s carcass.', 66);
insert into opinions (opinion, counter) values ('The philosophers have only interpreted the world in various ways; the point, however, is to change it.', 55);
insert into opinions (opinion, counter) values ('While the miser is merely a capitalist gone mad, the capitalist is a rational miser.', 11);
insert into opinions (opinion, counter) values ('Capital is money, capital is commodities. By virtue of it being value, it has acquired the occult ability to add value to itself. It brings forth living offspring, or, at the least, lays golden eggs.', 22);
insert into opinions (opinion, counter) values ('The only antidote to mental suffering is physical pain.', 75);
insert into opinions (opinion, counter) values ('The writer may very well serve a movement of history as its mouthpiece, but he cannot of course create it.', 84);
insert into opinions (opinion, counter) values ('The theory of the Communists may be summed up in the single sentence: Abolition of private property.', 90);
insert into opinions (opinion, counter) values ('Civil servants and priests, soldiers and ballet-dancers, schoolmasters and police constables, Greek museums and Gothic steeples, civil list and services list – the common seed within which all these fabulous beings slumber in embryo is taxation.', 53);
insert into opinions (opinion, counter) values ('The ideas of the ruling class are in every epoch the ruling ideas, i.e., the class which is the ruling material force of society, is at the same time its ruling intellectual force.', 30);
insert into opinions (opinion, counter) values ('It is absolutely impossible to transcend the laws of nature. What can change in historically different circumstances is only the form in which these laws expose themselves.', 10);
insert into opinions (opinion, counter) values ('Men make their own history.', 43);
insert into opinions (opinion, counter) values ('Surround yourself with people who make you happy. People who make you laugh, who help you when you’re in need. People who genuinely care. They are the ones worth keeping in your life. Everyone else is just passing through', 23);
